# SPDX-License-Identifier: GPL-2.0-only
ccflags-y := -I$(srctree)/security/abac_trees_enc/include/
obj-$(CONFIG_SECURITY_ABAC_TREES_ENC) := abac_lsm.o

obj-y := abacfs.o abac_lsm.o avp.o user.o env.o obj.o
