# SPDX-License-Identifier: GPL-2.0-only
ccflags-y := -I$(srctree)/security/abac_trees/include/
obj-$(CONFIG_SECURITY_ABAC_TREES) := abac_lsm.o

obj-y := abacfs.o abac_lsm.o avp.o cache.o user.o env.o obj.o
